# Generated by Django 4.2.7 on 2025-09-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="playlists/thumbnails/"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("entertainment", "Entertainment"),
                            ("music", "Music"),
                            ("education", "Education"),
                            ("news", "News"),
                            ("sports", "Sports"),
                            ("gaming", "Gaming"),
                            ("technology", "Technology"),
                            ("cooking", "Cooking"),
                            ("travel", "Travel"),
                            ("lifestyle", "Lifestyle"),
                            ("business", "Business"),
                            ("comedy", "Comedy"),
                            ("health", "Health"),
                            ("art", "Art"),
                            ("religion", "Religion"),
                            ("politics", "Politics"),
                            ("regional", "Regional Content"),
                        ],
                        default="entertainment",
                        max_length=20,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(upload_to=videos.models.video_upload_path),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=videos.models.thumbnail_upload_path,
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "resolution_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "resolution_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fps", models.FloatField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "age_restriction",
                    models.CharField(
                        choices=[("all", "All Ages"), ("13+", "13+"), ("18+", "18+")],
                        default="all",
                        max_length=5,
                    ),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_likes", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("dislike_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("language", models.CharField(default="en", max_length=10)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="accounts.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.video"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                related_name="playlists",
                through="videos.PlaylistVideo",
                to="videos.video",
            ),
        ),
        migrations.CreateModel(
            name="VideoQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("360p", "360p"),
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                            ("1440p", "1440p"),
                            ("2160p", "2160p (4K)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("bitrate", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-quality"],
                "unique_together": {("video", "quality")},
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["visibility", "processing_status"],
                name="videos_vide_visibil_e48887_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category", "uploaded_at"],
                name="videos_vide_categor_f48502_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["channel", "visibility"], name="videos_vide_channel_221573_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistvideo",
            unique_together={("playlist", "video")},
        ),
    ]
