# Generated by Django 4.2.7 on 2025-09-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("watch_time", models.DurationField()),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("quality_watched", models.CharField(default="auto", max_length=10)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("screen_resolution", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("referrer", models.URLField(blank=True)),
                ("traffic_source", models.CharField(blank=True, max_length=50)),
                ("liked", models.BooleanField(default=False)),
                ("commented", models.BooleanField(default=False)),
                ("shared", models.BooleanField(default=False)),
                ("subscribed_after", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video", "created_at"],
                        name="streaming_v_video_i_cdc9f0_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="streaming_v_user_id_a191a5_idx",
                    ),
                    models.Index(
                        fields=["country", "created_at"],
                        name="streaming_v_country_1f5643_idx",
                    ),
                    models.Index(
                        fields=["device_type", "created_at"],
                        name="streaming_v_device__5a1012_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("total_watch_time", models.DurationField(blank=True, null=True)),
                ("average_view_duration", models.DurationField(blank=True, null=True)),
                ("average_completion_rate", models.FloatField(default=0.0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("dislikes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("new_subscribers", models.PositiveIntegerField(default=0)),
                ("subscriber_views", models.PositiveIntegerField(default=0)),
                ("non_subscriber_views", models.PositiveIntegerField(default=0)),
                ("direct_views", models.PositiveIntegerField(default=0)),
                ("search_views", models.PositiveIntegerField(default=0)),
                ("social_views", models.PositiveIntegerField(default=0)),
                ("suggested_views", models.PositiveIntegerField(default=0)),
                ("mobile_views", models.PositiveIntegerField(default=0)),
                ("desktop_views", models.PositiveIntegerField(default=0)),
                ("tablet_views", models.PositiveIntegerField(default=0)),
                ("tv_views", models.PositiveIntegerField(default=0)),
                ("top_countries", models.JSONField(default=dict)),
                ("top_regions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["video", "date"], name="streaming_v_video_i_08d51c_idx"
                    ),
                    models.Index(
                        fields=["date", "views"], name="streaming_v_date_5adcec_idx"
                    ),
                ],
                "unique_together": {("video", "date")},
            },
        ),
        migrations.CreateModel(
            name="StreamingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("stream_key", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("peak_viewers", models.PositiveIntegerField(default=0)),
                ("total_viewers", models.PositiveIntegerField(default=0)),
                ("chat_messages", models.PositiveIntegerField(default=0)),
                ("allow_chat", models.BooleanField(default=True)),
                ("chat_slow_mode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_streams",
                        to="accounts.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
                "indexes": [
                    models.Index(
                        fields=["channel", "status"],
                        name="streaming_s_channel_d6f104_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_start"],
                        name="streaming_s_status_7131d6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChannelAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                ("total_watch_time", models.DurationField(blank=True, null=True)),
                ("subscribers_gained", models.IntegerField(default=0)),
                ("subscribers_lost", models.PositiveIntegerField(default=0)),
                ("total_subscribers", models.PositiveIntegerField(default=0)),
                ("videos_published", models.PositiveIntegerField(default=0)),
                ("total_videos", models.PositiveIntegerField(default=0)),
                ("total_likes", models.PositiveIntegerField(default=0)),
                ("total_comments", models.PositiveIntegerField(default=0)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ad_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="accounts.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["channel", "date"],
                        name="streaming_c_channel_e6d5cd_idx",
                    ),
                    models.Index(
                        fields=["date", "total_views"],
                        name="streaming_c_date_14549c_idx",
                    ),
                ],
                "unique_together": {("channel", "date")},
            },
        ),
    ]
